import type { PaymentReceipt } from "@workspace/api-client-react";

const METHOD_LABELS: Record<string, string> = {
  cash: "Cash",
  eft: "EFT / Bank Transfer",
  credit_card: "Credit Card",
  debit_card: "Debit Card",
  direct_deposit: "Direct Deposit",
};

function escapeHtml(value: unknown): string {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function formatMoney(cents: number): string {
  return `R ${(cents / 100).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`;
}

function formatDate(value: string): string {
  return new Date(value).toLocaleString("en-ZA", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function slipHtml(receipt: PaymentReceipt): string {
  const rows = [
    ["Receipt No.", receipt.referenceNumber],
    ["Payment ID", receipt.paymentId],
    ["Learner", receipt.learnerName],
    ["Admission No.", receipt.admissionNumber],
    ["Description", receipt.description],
    ["Payment Method", METHOD_LABELS[receipt.paymentMethod] ?? receipt.paymentMethod],
    ["Processed", formatDate(receipt.processedAt)],
  ];

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Payment Slip ${escapeHtml(receipt.referenceNumber)}</title>
    <style>
      * { box-sizing: border-box; }
      body {
        margin: 0;
        padding: 32px;
        background: #f4f7fb;
        color: #111827;
        font-family: Arial, Helvetica, sans-serif;
      }
      .slip {
        max-width: 460px;
        margin: 0 auto;
        background: white;
        border: 1px solid #d8dee9;
        border-radius: 8px;
        padding: 28px;
      }
      .top {
        border-bottom: 2px solid #0f766e;
        padding-bottom: 16px;
        margin-bottom: 20px;
      }
      .school {
        font-size: 22px;
        font-weight: 700;
        margin: 0 0 4px;
      }
      .subtitle {
        color: #64748b;
        font-size: 13px;
        margin: 0;
      }
      .amount {
        margin: 22px 0;
        padding: 18px;
        background: #ecfdf5;
        border: 1px solid #a7f3d0;
        border-radius: 8px;
        text-align: center;
      }
      .amount-label {
        color: #047857;
        font-size: 12px;
        font-weight: 700;
        text-transform: uppercase;
      }
      .amount-value {
        color: #065f46;
        font-size: 30px;
        font-weight: 800;
        margin-top: 4px;
      }
      .row {
        display: flex;
        justify-content: space-between;
        gap: 20px;
        border-bottom: 1px solid #e5e7eb;
        padding: 10px 0;
        font-size: 14px;
      }
      .row span:first-child {
        color: #64748b;
      }
      .row span:last-child {
        text-align: right;
        font-weight: 600;
      }
      .footer {
        margin-top: 22px;
        color: #64748b;
        font-size: 12px;
        text-align: center;
      }
      @media print {
        body { background: white; padding: 0; }
        .slip { border: none; max-width: none; }
      }
    </style>
  </head>
  <body>
    <main class="slip">
      <section class="top">
        <p class="school">${escapeHtml(receipt.schoolName)}</p>
        <p class="subtitle">Official payment slip</p>
      </section>
      <section class="amount">
        <div class="amount-label">Amount Paid</div>
        <div class="amount-value">${escapeHtml(formatMoney(receipt.amount))}</div>
      </section>
      ${rows
        .map(
          ([label, value]) => `<div class="row"><span>${escapeHtml(label)}</span><span>${escapeHtml(value)}</span></div>`,
        )
        .join("")}
      <p class="footer">Generated by SA School Management System</p>
    </main>
  </body>
</html>`;
}

export function openPaymentSlipWindow(): Window | null {
  const printWindow = window.open("", "_blank", "width=520,height=720");

  if (printWindow) {
    printWindow.document.write(
      "<!doctype html><title>Payment Slip</title><body style=\"font-family: Arial, sans-serif; padding: 24px;\">Preparing payment slip...</body>",
    );
    printWindow.document.close();
  }

  return printWindow;
}

export function printPaymentSlip(
  receipt: PaymentReceipt,
  printWindow: Window | null = openPaymentSlipWindow(),
): boolean {
  if (!printWindow) {
    return false;
  }

  printWindow.document.open();
  printWindow.document.write(slipHtml(receipt));
  printWindow.document.close();
  printWindow.focus();
  window.setTimeout(() => printWindow.print(), 250);

  return true;
}
