kind = "web"
previewPath = "/"
title = "SA School Management System"
version = "1.0.0"
id = "artifacts/school-management"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23826

[services.development]
run = "pnpm --filter @workspace/school-management run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/school-management", "run", "build" ]
publicDir = "artifacts/school-management/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23826"
BASE_PATH = "/"
